use std::error::Error;

pub fn push() -> Result<(), Box<dyn Error>> {
    Ok(())
}

pub fn pull() -> Result<(), Box<dyn Error>> {
    Ok(())
}
